# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: "%env(APP_SECRET)%"

  messenger:
    transports:
      async: "%env(MESSENGER_TRANSPORT_DSN)%"
      sync: "sync://"

    routing:
      'App\Messenger\SyncMessage': sync
      'App\Messenger\AsyncMessage': async
