instrumentation:
  tracing:
    doctrine:
      instrumentation: true
      propagation: true
      log_queries: true
  metrics:
    request:
      enabled: true
    message:
      enabled: true

monolog:
  handlers:
    otel:
      type: service
      id: Instrumentation\Logging\OtelHandler
